name: Hello Docker
author: Olzhas Seitmagambet
description: Create Github Issue
inputs:
  name:
    description: Name
    required: true
outputs:
  time:
    description: the greeting time
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.name }}