name: Notify on Issue

on:
  issues:
    types: [opened]

jobs:
  slack-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send Slack Message
        uses: ./.github/actions/send-slack-message
        with:
          message: 'New Issue Created: ${{ github.event.issue }} is out, <${{ github.event.issue.html_url }}|${{ github.event.issue.title }}>'
          webhook: ${{ secrets.SLACK_WEBHOOK }}
