on: push
jobs: 
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello-docker
        id: hello
        with:
          name: Docker
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo $HELLO
