name: CI

on: 
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Check code format
        run: yarn format:check
      - name: Run tests
        run: yarn test:coverage
        env: 
          CI: true
