name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: |
          cd ..
          pwd
      - run: pwd
      - run: yarn install --frozen-lockfile 
      - run: yarn build
      - run: ls -R
  next:
    runs-on: ubuntu-latest
    steps: 
      - run: pwd
      - run: ls -R

