name: CI

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Check code format
        run: yarn format:check
      - name: Run tests
        run: yarn test:coverage
        env:
          CI: true
      - name: Build Project
        if: github.event_name == 'push'
        run: yarn build
      - run: yarn add -g surge
      - name: Deploy to Staging
        if: github.event_name == 'push'
        run: npx surge --project ./dist --domain akira-staging.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}


