name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pwd
          ls -R
      - uses: actions/checkout@v2
      - run: |
          pwd
          ls -R
      - run: |
          cd ..
          pwd
          ls
      - run: |
          pwd
          ls
      - run: yarn install --frozen-lockfile 
      - run: yarn build
      - run: ls -R

