name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Home $HOME"
          echo "Workspace $GITHUB_WORKSPACE"
          echo "pwd $(pwd)"

      - name: Checkout 
        uses: actions/checkout@v2

      - name: Remove Git
        run: rm -rf .git

      - name: Install 
        run: yarn install --frozen-lockfile 

      - name: Build
        run: yarn build

      - run: |
          echo "$GITHUB_ACTOR/$GITHUB_ACTOR.github.io"
          echo "$HOME/work/$GITHUB_ACTOR"
          echo "${{ toJSON(env) }}"

      - name: Pull Github Pages
        uses: actions/checkout@v2
        with: 
          repository: winexy/winexy.github.io
          path: "github-pages"

      - run: |
          pwd
          ls 
          mv dist ./github-pages/akira
          cd ./github-pages
          git status
          git config --global user.email "robot@winex.github.io"
          git config --global user.name "Robokek"
          git commit -am "upload akira"
          git status
          git log


